language: java
notifications:
  slack:
    secure: KJ7CEjnt7eyoGgcFhlwZS5p+PQBoTdV9H9/Kii0JmG0L0SRgzOh0r41zdoU49TdPJD5Y0/z135TYBms+ce4Cd/yiVc3jVeGevziHDnlHT0JS0MBG7RR3yLbgHcVVdIGA5bAJcByGkHM8Mgi0jOIB9Wt/NwwqNmlIYASS6kvsqOo=
